# Generated by Django 2.1.1 on 2018-09-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=60)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.NullBooleanField()),
                ('numExistencias', models.IntegerField(default=0)),
            ],
        ),
    ]
